--COUNTRY TABLE
CREATE TABLE country
(
    id        bigint generated by default as identity primary key,
    name      VARCHAR(255) NOT NULL,
    continent VARCHAR(255) NOT NULL
);

-- HOST TABLE
CREATE TABLE host
(
    id         bigint generated by default as identity primary key,
    name       VARCHAR(255) NOT NULL,
    surname    VARCHAR(255) NOT NULL,
    country_id BIGINT REFERENCES country (id)
);

--ACCOMMODATION TABLE
CREATE TABLE accommodation
(
    id        bigint generated by default as identity primary key,
    name      VARCHAR(255) NOT NULL,
    category  VARCHAR(255) NOT NULL,
    host_id   BIGINT REFERENCES host (id),
    numRooms  INT,
    is_Rented BOOLEAN DEFAULT FALSE
);

-- USER TABLE (accommodations_users)
CREATE TABLE accommodations_users
(
    username                   VARCHAR(255) PRIMARY KEY,
    password                   VARCHAR(255) NOT NULL,
    name                       VARCHAR(255) NOT NULL,
    surname                    VARCHAR(255) NOT NULL,
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled                 BOOLEAN DEFAULT TRUE,
    role                       VARCHAR(255)
);

-- BOOKING TABLE
CREATE TABLE booking
(
    id             bigint generated by default as identity primary key,
    date           TIMESTAMP,
    user_username  VARCHAR(255),
    booking_status VARCHAR(255),
    CONSTRAINT fk_booking_user FOREIGN KEY (user_username) REFERENCES accommodations_users (username)
);

-- JOIN TABLE FOR booking_accommodations (ManyToMany)
CREATE TABLE booking_accommodations
(
    booking_id       BIGINT REFERENCES booking (id),
    accommodation_id BIGINT REFERENCES accommodation (id),
    PRIMARY KEY (booking_id, accommodation_id)
);